export type {
  AgentContext,
  AgentRunResult,
  AgentOptions,
  AgentName,
  ConfigureAgentOptions,
} from "./types.js";

export { a_workspace, cleanup_workspace, AGENTS_GWT_TMP_ROOT } from "./given/a_workspace.js";
export { copy_to_workspace, type CopyToWorkspaceOptions } from "./given/copy_to_workspace.js";
export { the_prompt } from "./given/the_prompt.js";
export { executing_the_agent } from "./when/executing_the_agent.js";
export { agent } from "./given/agent.js";

export {
  Agent,
  createAgent,
  type CreateAgentBindings,
  type AgentBinding,
  type TokenUsage,
  type StockAgentName,
  bindingRegistry,
  registerBinding,
  unregisterBinding,
  resetBindings,
  resolveBinding,
  buildImages,
  resetBuildMemo,
  type BuildImagesOptions,
  resolveImage,
  readRegistry,
  resetRegistry,
  upsertRegistryEntry,
  BASE_IMAGE,
  CONTAINER_HOME,
  CONTAINER_INPUT,
  CONTAINER_OUTPUT,
  CONTAINER_WORKSPACE,
  PACKAGE_ROOT,
  AgentFs,
  type AgentFsOptions,
  ensureDockerImage,
  parseAgentJsonOutput,
  buildDockerRunArgs,
  invokeDocker,
  runDocker,
  runBoundAgent,
  type DockerRunner,
  type DockerRunOptions,
  type DockerRunResult,
  type BuildDockerRunArgsOptions,
  type DockerVolumeMount,
  type RunAgentOptions,
  type AgentRunBindingsOptions,
  TRAJECTORY_FILE,
  CONTAINER_TRAJECTORY_PATH,
  parseTrajectory,
  readTrajectory,
  asRecord,
  extractTextContent,
  readString,
  type Trajectory,
  type TrajectoryAdapter,
  type TrajectoryEvent,
  type TrajectoryKind,
  type TrajectoryToolCall,
} from "clanker-cleanroom";
